# Generated by Django 4.1.1 on 2023-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket_quantity_frame_quantity_seat_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
