# Generated by Django 4.1.1 on 2023-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_bike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
